version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - docker build -t kemu-site . --file dockerfiles/Dockerfile-web
      - docker build -t kemu-site-nginx . --file dockerfiles/Dockerfile-nginx
  post_build:
    commands:
      - VERSION=`git rev-parse --short HEAD`
      - docker tag kemu-site 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com/kemu-site:latest
      - docker tag kemu-site 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com/kemu-site:$VERSION
      - docker tag kemu-site-nginx 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com/kemu-site-nginx:latest
      - docker tag kemu-site-nginx 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com/kemu-site-nginx:$VERSION
      - docker push -a 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com/kemu-site
      - docker push -a 535811171857.dkr.ecr.ap-northeast-1.amazonaws.com/kemu-site-nginx
