version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./src/static:/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    working_dir: /app/src/
    entrypoint: "/bin/sh '/app/entrypoint/django.sh'" 
    command: uwsgi --http :8000 --module apps.wsgi --enable-threads
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env_release
