version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-nginx
    volumes:
      - ./src/static:/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-web
    working_dir: /app/src/
    entrypoint: "/bin/sh '/app/entrypoint/django.sh'" 
    command: uwsgi --http :8000 --module apps.wsgi --enable-threads
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env_release
