# Generated by Django 2.2.1 on 2019-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('contents', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(blank=True)),
                ('published', models.DateTimeField()),
                ('terminated', models.DateTimeField(blank=True)),
            ],
        ),
    ]
