# Generated by Django 2.2.1 on 2019-05-19 08:50

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190519_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=markdownx.models.MarkdownxField(
                help_text='Markdown形式で書いてください。', verbose_name='本文'),
        ),
    ]
