# Generated by Django 2.2.1 on 2019-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190519_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='terminated',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateField(),
        ),
    ]
