# Generated by Django 2.2.1 on 2019-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190519_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateField(null=True),
        ),
    ]
