# Generated by Django 2.2.1 on 2019-05-20 05:12

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190519_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('send_by', models.CharField(max_length=20)),
                ('created', models.DateTimeField()),
                ('contents', markdownx.models.MarkdownxField(
                    help_text='Markdown形式で書いてください。', verbose_name='コメント')),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
