# Generated by Django 2.2.1 on 2019-05-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_comment', to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_post', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='send_by',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
    ]
