# Generated by Django 2.2.1 on 2019-06-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20190529_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=100),
        ),
    ]
