# Generated by Django 3.2.9 on 2021-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=32, verbose_name='タグ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('contents', models.TextField(verbose_name='記事')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('tags', models.ManyToManyField(related_name='ref_articles', to='article.Tag', verbose_name='タグ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
