# Generated by Django 3.2.9 on 2021-11-14 11:47

import uuid

from django.db import migrations, models


def set_default_uuid(apps, schema):
    Article = apps.get_model("article", "Article")
    articles = Article.objects.all()
    for article in articles:
        article.uuid = uuid.uuid4()
    Article.objects.bulk_update(articles, fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.RunPython(set_default_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
