# Generated by Django 3.2.9 on 2021-11-15 13:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#6c757d', max_length=18),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='ref_articles', to='article.Tag', verbose_name='タグ'),
        ),
    ]
