# Generated by Django 3.2.9 on 2021-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='管理者からのコメント'),
        ),
    ]
