# Generated by Django 3.2.9 on 2021-11-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comment_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_viewer',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IPアドレス'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='アクセス数'),
        ),
    ]
