# Generated by Django 3.2.9 on 2021-11-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20211118_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='tag',
            name='ordering',
            field=models.IntegerField(default=9999, verbose_name='並び順'),
        ),
    ]
