# Generated by Django 3.2.9 on 2021-11-13 09:29

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_default_user(apps, schema):
    User = apps.get_model("shared", "User")
    user = User.objects.create_superuser(
        username=os.environ.get("SUPERUSER_NAME"), 
        email=os.environ.get("SUPERUSER_EMAIL"),
    )
    user.password = make_password(os.environ.get("SUPERUSER_PASSWORD"))
    user.save()

def remove_default_user(apps, schema):
    User = apps.get_model("shared", "User")
    User.objects.filter(username=os.environ.get("SUPERUSER_NAME")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user, remove_default_user)
    ]
