name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: |
        pip install -r requirements-dev.txt
        make lint
